// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WCF.Config.Helper.MyService {
    
    
    [System.ServiceModel.ServiceContractAttribute(Namespace="WCF.Config.Helper.MyService")]
    public interface IMyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://provcon-faust/TestWCF/IMyService/Hello", ReplyAction="http://provcon-faust/TestWCF/IMyService/HelloResponse")]
        string Hello();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://provcon-faust/TestWCF/IMyService/Test", ReplyAction="http://provcon-faust/TestWCF/IMyService/TestResponse")]
        int Test();
    }
    
    public interface IMyServiceChannel : IMyService, System.ServiceModel.IClientChannel {
    }
    
    public class MyServiceClient : System.ServiceModel.ClientBase<IMyService>, IMyService {
        
        public MyServiceClient() {
        }
        
        public MyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
                base(binding, endpoint) {
        }
        
        public string Hello() {
            return base.Channel.Hello();
        }
        
        public int Test() {
            return base.Channel.Test();
        }
    }
}
